### ISSUE TITLE
After latest update, tests with assertFormHasTextInput fail

### ISSUE THREAD

**Issue by gluis** [jcergolj/laravel-view-test-assertions#4]
First off, this is such a great and needed idea for laravel testing. Thanks for sharing!

Next, I don't know if the API has changed or not? I didn't see anything different in the README. 

I updated some other libraries in the project and ran a composer update. I hadn't checked to see if the versions of laravel-view-test-assertions changed or not but I'm guessing it has since the latest version is marked 24 days old (v1.0). 

Now, the same tests, using the same forms, produces a failed test using `assertFormHasTextInput`:

e.g. 
`->assertFormHasTextInput('name')`

Form HTML:
`<input wire:model="name" type="text" name="name" id="name" autofocus >`

Failed test text:
```
  Form does not have text field named name.
  Failed asserting that an object is not empty.

  at vendor/jcergolj/laravel-view-test-assertions/src/ViewTestAssertions.php:271
    267▕             if ($value !== null && $type !== 'select') {
    268▕                 $filterable .='[value="'.$value.'"]';
    269▕             }
    270▕ 
  ➜ 271▕             Assert::assertNotEmpty($form->filter($filterable), $msg);
    272▕ 
    273▕             return $this;
    274▕         };
    275▕     }

      +3 vendor frames 
  4   tests/Feature/SupportingDataControllerTest.php:147
      Illuminate\Testing\TestResponse::__call("assertFormHasTextInput")
```

Using: 
`"jcergolj/laravel-view-test-assertions": "^1.0",`

Let me know if any more information would be helpful.

**Comment by jcergolj** [comment]
Hi gluis, actually in 2.x version the first method attribute is now form's selector. Please see the docs. Thanks.

**Comment by gluis** [comment]
Sounds good! Thanks!
